### ISSUE TITLE
Upload library to public maven repository

### ISSUE THREAD

**Issue by nilsmagnus** [finn-no/retriable-kafka-consumer#2]
Upload library to a public maven repository

**Comment by nilsmagnus** [comment]
Following this guide: https://dzone.com/articles/comprehensive-step-by-step-guide-on-how-to-upload

**Comment by nilsmagnus** [comment]
@hennings , I need you (or someone else affiliated with finn.no) to comment on this issue: https://issues.sonatype.org/browse/OSSRH-47559

**Comment by ivarconr** [comment]
Ikke for å være vanskelig, men tidligere besluttet vi en gang at open source skjer med pakkestruktur no.finn.*

**Comment by nilsmagnus** [comment]
Hmm, godt mulig du har rett i at pakkenavnet skal være no.finn, @hennings kan du bekrefte/avkrefte?

**Comment by nilsmagnus** [comment]
Finner ingenting i maven central med prefix no.finn, men finner 1 bibliotek med no.finntech.  @ivarconr

**Comment by nilsmagnus** [comment]
Brukte no.finntech nå. Si fra hvis dere vil at jeg skal endre det, så fikser vi det.

**Comment by ivarconr** [comment]
> Finner ingenting i maven central med prefix no.finn

det er fordi vi har brukt sonatype:
https://oss.sonatype.org/#nexus-search;quick~no.finn

**Comment by nilsmagnus** [comment]
Ok. Skal jeg endre det til no.finntech? Er ikke noe stress og jeg har ikke noen sterke meninger. Må bare ha en regel å forholde meg til :smile:
